update ihpone 11

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -9,6 +9,7 @@ on:
 jobs:
   test:
     runs-on: macos-14-xlarge
+
     steps:
       - uses: actions/checkout@v2
 
@@ -17,15 +18,15 @@ jobs:
         with:
           access_token: ${{ github.token }}
 
-      # Installer la dernière version stable d'Xcode
+      # Installer la dernière version stable d'Xcode (16.2 ici)
       - uses: maxim-lobanov/setup-xcode@v1
         with:
-          xcode-version: latest
+          xcode-version: "16.2"
 
       # Installer une version stable de Ruby (par exemple 3.2.0)
       - uses: ruby/setup-ruby@v1
         with:
-          ruby-version: "3.2.0"  # Remplacez "latest" par une version spécifique de Ruby
+          ruby-version: "3.2.0"
 
       # Installer la dernière version de Bundler
       - name: Install Bundler
@@ -46,21 +47,32 @@ jobs:
           key: ${{ runner.os }}-deps-v1-${{ hashFiles('BILDsolid.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
           restore-keys: ${{ runner.os }}-deps-v1-
 
-      # Lister les simulateurs disponibles
+      # Lister les simulateurs disponibles pour vérifier iPhone 11 ou iPhone 12 avec iOS 16.2
       - name: List Available Simulators
         run: |
           xcrun simctl list devices
-          
+
+      # Démarrer le simulateur iPhone 11 avec iOS 16.2
+      - name: Start iPhone 11 Simulator with iOS 16.2
+        run: |
+          # Lister les simulateurs disponibles et démarrer le simulateur iPhone 11
+          SIMULATOR_ID=$(xcrun simctl list devices | grep "iPhone 11" | head -n 1 | awk -F '[(|)]' '{print $2}')
+          if [ -z "$SIMULATOR_ID" ]; then
+            echo "iPhone 11 Simulator not found, aborting"
+            exit 1
+          fi
+          echo "Booting iPhone 11 Simulator with ID: $SIMULATOR_ID"
+          xcrun simctl boot $SIMULATOR_ID
+          xcrun simctl list devices
+
       # Exécution des tests (sans cache)
       - name: Run Tests (No Cache)
         if: steps.setup.outputs.cache-hit != 'true'
         run: |
-          # Exécuter les tests sur l'iPhone 11 avec iOS 16.2
-          bundle exec fastlane ios unit_test clean:true skip_package_dependencies_resolution:true platform=ios simulator='iPhone 11' os='16.2'
+          bundle exec fastlane ios unit_test clean:true skip_package_dependencies_resolution:true platform=ios simulator="iPhone 11" os="16.2"
 
       # Exécution des tests (avec cache)
       - name: Run Tests (Cache)
         if: steps.setup.outputs.cache-hit == 'true'
         run: |
-          # Exécuter les tests avec cache sur l'iPhone 11 avec iOS 16.2
-          bundle exec fastlane ios unit_test clean:true skip_package_dependencies_resolution:true platform=ios simulator='iPhone 11' os='16.2'
+          bundle exec fastlane ios unit_test clean:true skip_package_dependencies_resolution:true platform=ios simulator="iPhone 11" os="16.2"
